
library(dplyr)

B1_S1 <- tbl_df(read.table('D:/Box Sync/Rhesus_Embryos/update_2017/Geoff_counts/rh150409-1-b1-B1_S1.q30.sort.bam.bin_4000_counts.txt',
                           header=T))

B1_S1

B1_S1.chr3 <- B1_S1 %>% filter(chr=='chr3')
plot(B1_S1.chr3$ratio)
plot(B1_S1.chr3$ratio[40:80])
which(B1_S1.chr3$ratio < 0.8)
# Looks like bins 59-64

# Check other samples
counts <- list()
i <- 0
# Read in counts
for(f in list.files('D:/Box Sync/Rhesus_Embryos/Geoff_counts/')) {
  i <- i + 1
  counts[[i]] <- tbl_df(read.table(paste0('D:/Box Sync/Rhesus_Embryos/update_2017/Geoff_counts/', f),
                                   header=T))
}

# Plot chr3 ratios
for(i in 1:length(counts)) {
  chr3 <- counts[[i]] %>% filter(chr=='chr3') %>% select(ratio) %>% as.matrix
  plot(chr3)
  low[[i]] <- which(chr3 < 0.8)
  # print(low[[i]])
}
tab.low <- table(unlist(low))
barplot(tab.low)
bad.bins <- names(tab.low[tab.low > 20])

# Plot chr3 counts
for(i in 1:length(counts)) {
  chr3 <- counts[[i]] %>% filter(chr=='chr3') %>% select(count) %>% as.matrix
  plot(chr3)
  # low[[i]] <- which(chr3 < 0.8)
  # print(low[[i]])
}
tab.low <- table(unlist(low))
barplot(tab.low)
bad.bins <- names(tab.low[tab.low > 20])


filter(counts[[1]], chr=='chr3')[as.numeric(bad.bins),]

# Do the same for chrom 17:
low <- list()
for(i in 1:length(counts)) {
  chr17 <- counts[[i]] %>% filter(chr=='chr17') %>% select(ratio) %>% as.matrix
  plot(chr17)
  low[[i]] <- which(chr17 < 0.7)
  # print(low[[i]])
}
tab.low <- table(unlist(low))
barplot(tab.low)
bad.bins <- names(tab.low[tab.low > 20])

filter(counts[[1]], chr=='chr17')[as.numeric(bad.bins),]

# Look at the windows generated by Geoff
win2k <- read.table('D:/Box Sync/Rhesus_Embryos/update_2017/WINDOWS/xx-bins_rheMac8_2000.txt')
win4k <- read.table('D:/Box Sync/Rhesus_Embryos/update_2017/WINDOWS/xx-bins_8_4000.txt')
